main: pb.ajneb97.PaintballBattle
version: 1.11.2
name: PaintballBattle
api-version: 1.21
author: Ajneb97
softdepend: [Multiverse-Core, DecentHolograms, Vault, PlaceholderAPI]

commands:
  paintball:
    description: Main command of PaintballBattle
    aliases: pb